apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-token
  namespace: jenkins
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical-cloud
    kind: ClusterSecretStore
  target:
    name: harbor-token
    creationPolicy: Owner
  data:
    - secretKey: .dockerconfigjson
      remoteRef:
        key: /harbor/.dockerconfigjson