apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-consumer
  name: kafka-consumer
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-consumer
  template:
    metadata:
      labels:
        app: kafka-consumer
    spec:
      containers:
        - name: kafka-consumer
          image: ghcr.io/serhiimyronets/consumer:latest
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          envFrom:
            - secretRef:
                name: postgresql-secret
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: my-cluster-kafka-bootstrap:9093
            - name: TOPIC
              value: sensor-data
          volumeMounts:
            - name: cluster-ca
              mountPath: /etc/kafka/ca
              readOnly: true
            - name: user-tls
              mountPath: /etc/kafka/user
              readOnly: true
      volumes:
        - name: cluster-ca
          secret:
            secretName: my-cluster-cluster-ca-cert
        - name: user-tls
          secret:
            secretName: kafka-test-apps-consumer