crds:
  enabled: false


kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false
kubeProxy:
  enabled: false

prometheus:
  prometheusSpec:
    retention: 7d
    retentionSize: "10GB"
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: local-nvme
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 20Gi

    # English comment: Talos-specific fix for node-exporter
    # It avoids issues with mounting host paths
    hostNetwork: true

grafana:
  grafana.ini:
    auth.anonymous.enabled: true
    auth.anonymous.org_role: Admin
    auth.anonymous.org_name: "Main Org."
    auth.disable_login_form: true
#  enabled: true
#  # English comment: Basic resources for Grafana
#  grafana.ini:
#    auth:
#      disable_login_form: true
#    auth.anonymous:
#      enabled: true
#      org_name: "Main Org."
#      org_role: Admin
  deploymentStrategy:
    type: Recreate
  adminPassword: "admin"

  # English comment: Ensure security context is still there
  securityContext:
    runAsUser: 472
    runAsGroup: 472
    fsGroup: 472
  initChownData:
    enabled: false
  
  persistence:
    enabled: true
    storageClassName: local-nvme
    size: 5Gi

  # English comment: Sidecar will automatically find dashboards in ConfigMaps
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      searchNamespace: ALL
