config:
  redirectURL: "https://oauth.serhii.link/oauth2/callback"
  upstreams:
    - static://200
  existingSecret: oauth2-proxy-token
  configFile: |
    provider = "github"
    scope = "user:email read:org"
    email_domains = [ "*" ]
    cookie_domains = [ ".serhii.link" ]
    whitelist_domains = [ ".serhii.link" ]
    cookie_secure = true
    github_users = [ "SerhiiMyronets" ]


ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  hosts:
    - oauth.serhii.link