tunnelConfig:
  name: wildcard-tunnel

tunnelSecrets:
  existingConfigJsonFileSecret:
    name: cloudflared-credential-token
    key: "credentials.json"

ingress:
  - hostname: "*.serhii.link"
    service: hhttp://cilium-gateway-main-gateway.gateway-system.svc.cluster.local:80

  - service: http_status:404