tunnelConfig:
  name: wildcard-tunnel

tunnelSecrets:
  base64EncodedPemFile: "dW51c2VkCg==" # "unused"

  existingConfigJsonFileSecret:
    name: cloudflared-credential-token
    key: "credentials.json"

ingress:
  - hostname: "*.serhii.link"
    service: hhttp://cilium-gateway-main-gateway.gateway-system.svc.cluster.local:80

  - service: http_status:404

replica:
  allNodes: false
  count: 1