config:
  inputs: |
    [INPUT]
        Name                tail
        Tag                 kube.*
        Path                /var/log/containers/*_kube-system_*.log
        Parser              cri
        Mem_Buf_Limit       100MB
        Refresh_Interval    10

  filters: |
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_Tag_Prefix     kube.var.log.containers.
        Merge_Log           On
        Keep_Log            Off
        K8S-Logging.Parser  On
        K8S-Logging.Exclude On
        Labels              On
        Annotations         On

    [FILTER]
        Name                modify
        Match               kube.*
        Add                 log_type infrastructure

  outputs: |
    [OUTPUT]
        Name                   opentelemetry
        Match                  *
        Host                   otel-gateway-collector.observability.svc
        Port                   4318
        Logs_uri               /v1/logs
        Log_response_payload   False
        Tls                    Off
        resource_attributes    k8s.pod.name=$kubernetes['pod_name'] \
                               k8s.namespace.name=$kubernetes['namespace_name'] \
                               k8s.container.name=$kubernetes['container_name'] \
                               k8s.pod.labels.app=$kubernetes['labels']['app'] \
                               service.name=$kubernetes['pod_name']
        logs_attributes        log=$log \
                               kubernetes_namespace=$kubernetes['namespace_name'] \
                               kubernetes_pod=$kubernetes['pod_name']