config:
  service:
    log_level: info
    http_listen: 0.0.0.0

  pipeline:
    inputs:
      - name: tail
        alias: k8s-logs
        path: /var/log/containers/*_kube-system_*.log
        exclude_path: /var/log/containers/*fluent-bit*.log,/var/log/containers/*fluentbit*.log
        tag: kube.*
        read_from_head: true
        multiline.parser: cri
        skip_long_lines: true
        skip_empty_lines: true
        refresh_interval: 10
        mem_buf_limit: 50MB

    filters:
      - name: kubernetes
        match: kube.*
        merge_log: false
        keep_log: true
        labels: true
        annotations: true

      - name: modify
        match: kube.*
        add: log_type infrastructure

      - name: modify
        match: kube.*
        add: fb_marker __from_fluent_bit__

    outputs:
      - name: stdout
      - match: kube.*
      - name: opentelemetry
        match: kube.*
        host: otel-gateway-collector.observability.svc
        port: 4318
        logs_uri: /v1/logs
        tls: off