# values-collector.yaml для fluent-bit-collector

image:
  repository: ghcr.io/fluent/fluent-bit
  tag: 4.2.2  # твоя версія
  pullPolicy: IfNotPresent

daemonset:
  enabled: true

config:
  service:
    log_level: info
    http_listen: 0.0.0.0

  pipeline:
    inputs:
      - name: tail
        alias: k8s-logs
        path: /var/log/containers/*_kube-system_*.log   # тільки kube-system для тесту
        exclude_path: /var/log/containers/*fluent-bit*.log,/var/log/containers/*fluentbit*.log
        tag: kube.*   # або kube.<namespace_name>.<pod_name>.<container_name> для кращої сумісності
        read_from_head: true
        multiline.parser: cri
        skip_long_lines: true
        skip_empty_lines: true
        refresh_interval: 10
        mem_buf_limit: 50MB

    filters:
      - name: kubernetes
        match: kube.*
        kube_tag_prefix: kube.var.log.containers.
        merge_log: true
        keep_log: false
        k8s-logging.parser: true
        k8s-logging.exclude: true
        labels: true
        annotations: true

      - name: modify
        match: kube.*
        add: log_type infrastructure

    outputs:
      - name: opentelemetry
        match: "*"
        host: otel-gateway-collector.observability.svc
        port: 4318
        logs_uri: /v1/logs
        log_response_payload: false
        tls: off