apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-jcasc-config
  namespace: jenkins
  labels:
    jenkins-jenkins-config: "true"
data:
  jcasc.yaml: |
    jenkins:
      numExecutors: 1
      mode: NORMAL
      markupFormatter:
        plainText: {}
          
      systemMessage: "🔧 Jenkins configured via JCasC"
              
          
      clouds:
        - kubernetes:
            name: "kubernetes"
            serverUrl: "https://kubernetes.default"
            jenkinsUrl: "http://jenkins.jenkins.svc.cluster.local:8080"
            jenkinsTunnel: "jenkins-agent.jenkins.svc.cluster.local:50000"
            containerCapStr: "10"
            namespace: "jenkins"
    
    credentials:
      system:
        domainCredentials:
          - credentials:
              - string:
                  scope: GLOBAL
                  id: sonar-token
                  description: "SonarQube Token"
                  secret: ${SONAR_TOKEN}
              - string:
                  scope: GLOBAL
                  id: gihub-only-token
                  description: "Github only Token"
                  secret: ${GITHUB_ACCESS_TOKEN}
              - usernamePassword:
                  scope: GLOBAL
                  id: github-access-token
                  description: "Github Access Token"
                  username: ${GITHUB_ACCESS_USERNAME}
                  password: ${GITHUB_ACCESS_TOKEN}
                    
    unclassified:
      location:
        url: https://jenkins.cluster
      sonarGlobalConfiguration:
        buildWrapperEnabled: true
        installations:
        - credentialsId: "sonar-token"
          name: "SonarQube"
          serverUrl: "http://sonarqube-sonarqube.sonarqube.svc.cluster.local:9000"
      globalLibraries:
        libraries:
          - defaultVersion: "main"
            name: "jenkins-shared-lib"
            retriever:
              modernSCM:
                scm:
                  git:
                    id: jenkins-shared-lib
                    credentialsId: "github-access-token"
                    remote: "https://github.com/DevSecOps-homelab/jenkins-shared-lib"
                    traits:
                      - "gitBranchDiscovery"
    
    
    security:
      apiToken:
        creationOfLegacyTokenEnabled: false
        tokenGenerationOnCreationEnabled: false
        usageStatisticsEnabled: true
    
    appearance:
      prism:
        theme: PRISM
      themeManager:
        disableUserThemes: false
        theme: "darkSystem"
        
        
    jobs:
    - script: >
        job('seed-job') {
          description('Seed job to create multibranch jobs via DSL')
          scm {
            git {
              remote {
                url('https://github.com/SerhiiMyronets/terraform-talos-gitops-homelab')
                credentials('github-access-token')
              }
              branch('homelab')
            }
          }
          triggers {
            scm('H/5 * * * *')
          }
          steps {
            dsl {
              external('03-gitops/apps/04-ci-cd/jenkins/jobs/*.groovy')
              removeAction('DELETE')
              removeViewAction('DELETE')
            }
          }
        }