apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-jcasc-config
  namespace: jenkins
  labels:
    jenkins-jenkins-config: "true"
data:
  jcasc.yaml: |
    jenkins:
      numExecutors: 0
      mode: NORMAL
      markupFormatter:
        plainText: {}
          
      systemMessage: "🔧 Jenkins configured via JCasC"
              
          
      clouds:
        - kubernetes:
            name: "kubernetes"
            serverUrl: "https://kubernetes.default"
            jenkinsUrl: "http://jenkins.jenkins.svc.cluster.local:8080"
            jenkinsTunnel: "jenkins-agent.jenkins.svc.cluster.local:50000"
            containerCapStr: "10"
            namespace: "jenkins"
            templates:
              - name: "default"
                id: "default"
                label: "jenkins-agent"
                serviceAccount: "default"
                yamlMergeStrategy: override
                podRetention: Never
                containers:
                  - name: "jnlp"
                    image: "jenkins/inbound-agent:3327.v868139a_d00e0-2"
                    command: ""
                    args: "^${computer.jnlpmac} ^${computer.name}"
                    ttyEnabled: false
                    workingDir: "/home/jenkins/agent"
                    envVars:
                      - envVar:
                          key: "JENKINS_URL"
                          value: "http://jenkins.jenkins.svc.cluster.local:8080/"
              - name: "nodejs"
                label: "nodejs"
                id: "nodejs"
                yamlMergeStrategy: "override"
                containers:
                  - name: "node"
                    image: "node:24-alpine"
                    command: "cat"
                    ttyEnabled: true
                    workingDir: "/home/jenkins/agent"
                  - name: gitleaks
                    image: zricethezav/gitleaks:latest
                    command: "cat"
                    ttyEnabled: true
                    workingDir: "/home/jenkins/agent"
                  - name: sonar
                    image: sonarsource/sonar-scanner-cli:latest
                    command: "cat"
                    ttyEnabled: true
                    workingDir: "/home/jenkins/agent"
                  - name: trivy
                    image: aquasec/trivy:latest
                    command: "sleep"
                    args: "infinity"
                    ttyEnabled: true
                    workingDir: "/home/jenkins/agent"
                  - name: kaniko
                    image: volkamana/kaniko:v5
                    workingDir: "/home/jenkins/agent/workspace/ci"
                volumes:
                  - secretVolume:
                      mountPath: "/kaniko/.docker"
                      optional: false
                      secretName: "regcred"


    
    credentials:
      system:
        domainCredentials:
          - credentials:
              - string:
                  scope: GLOBAL
                  id: sonar-token
                  description: "SonarQube Token"
                  secret: ${SONAR_TOKEN}
                    
    unclassified:
      location:
        url: https://jenkins.cluster
      sonarGlobalConfiguration:
        buildWrapperEnabled: true
        installations:
        - credentialsId: "sonar-token"
          name: "SonarQube"
          serverUrl: "http://sonarqube-sonarqube.sonarqube.svc.cluster.local:9000"
    
    
    security:
      apiToken:
        creationOfLegacyTokenEnabled: false
        tokenGenerationOnCreationEnabled: false
        usageStatisticsEnabled: true
    
    appearance:
      prism:
        theme: PRISM
      themeManager:
        disableUserThemes: false
        theme: "darkSystem"
