apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-jcasc-config
  namespace: jenkins
  labels:
    jenkins-jenkins-config: "true"
data:
  jcasc.yaml: |
    jenkins:
      numExecutors: 0
      mode: NORMAL
      markupFormatter:
        plainText: {}
          
      systemMessage: "🔧 Jenkins configured via JCasC"
              
          
      clouds:
        - kubernetes:
            name: "kubernetes"
            serverUrl: "https://kubernetes.default"
            jenkinsUrl: "http://jenkins.jenkins.svc.cluster.local:8080"
            jenkinsTunnel: "jenkins-agent.jenkins.svc.cluster.local:50000"
            containerCapStr: "10"
            namespace: "jenkins"
            templates:
              - name: "default"
                id: "default"
                label: "jenkins-agent"
                serviceAccount: "default"
                yamlMergeStrategy: override
                podRetention: Never
                containers:
                  - name: "jnlp"
                    image: "jenkins/inbound-agent:3327.v868139a_d00e0-2"
                    command: ""
                    args: "^${computer.jnlpmac} ^${computer.name}"
                    ttyEnabled: false
                    resourceRequestCpu: "512m"
                    resourceRequestMemory: "512Mi"
                    resourceLimitCpu: "512m"
                    resourceLimitMemory: "512Mi"
                    workingDir: "/home/jenkins/agent"
                    envVars:
                      - envVar:
                          key: "JENKINS_URL"
                          value: "http://jenkins.jenkins.svc.cluster.local:8080/"
              - id: "nodejs"
                label: "nodejs"
                name: "nodejs"
                yamlMergeStrategy: "override"
                containers:
                  - args: "9999999"
                    command: "sleep"
                    image: "node:24-alpine"
                    name: "node"
                    ttyEnabled: true
                    workingDir: "/home/jenkins/agent"
                    
    unclassified:
      location:
        url: https://jenkins.cluster
        
    security:
      apiToken:
        creationOfLegacyTokenEnabled: false
        tokenGenerationOnCreationEnabled: false
        usageStatisticsEnabled: true
    
    appearance:
      prism:
        theme: PRISM
      themeManager:
        disableUserThemes: false
        theme: "darkSystem"
