apiVersion: v1
kind: Secret
metadata:
  name: sonar-token
  namespace: jenkins
type: Opaque
data:
  SONAR_HOST_URL: sonarqube-sonarqube.sonarqube.svc.cluster.local
  SONAR_TOKEN: c3FhXzE3N2U4ZThhN2ZiMTkxMWI3MDM5OWI0MDg2MjMzOTgwNDVlM2M5OTA=