apiVersion: v1
kind: Secret
metadata:
  name: sonar-token
  namespace: jenkins
type: Opaque
data:
  SONAR_HOST_URL: c29uYXJxdWJlLXNvbmFycWViZS5zb25hcnh1YmUuc3ZjLmNsdXN0ZXIubG9jYWw=
  SONAR_TOKEN: c3FhXzE3N2U4ZThhN2ZiMTkxMWI3MDM5OWI0MDg2MjMzOTgwNDVlM2M5OTA=