apiVersion: v1
kind: Secret
metadata:
  name: sonar-token
  namespace: jenkins
type: Opaque
data:
  SONAR_HOST_URL: aHR0cDovL3NvbmFycXViZS1zb25hcnF1YmUuc29uYXJxdWJlLnN2Yy5jbHVzdGVyLmxvY2FsOjkwMDA=
  SONAR_TOKEN: c3FhXzE3N2U4ZThhN2ZiMTkxMWI3MDM5OWI0MDg2MjMzOTgwNDVlM2M5OTA=