controller:
  installPlugins:
    - kubernetes
    - configuration-as-code
    - workflow-aggregator
    - git
    - dark-theme

  JCasC:
    enabled: true
    configMaps:
      - jenkins-jcasc

  ingress:
    enabled: false

persistence:
  enabled: true
#  existingClaim: jenkins-home