#controller:
#  installPlugins:
#    - kubernetes
#    - configuration-as-code
#    - workflow-aggregator
#    - git
#    - dark-theme

#  JCasC:
#    enabled: false
#    configMaps:
#      - jenkins-jcasc


controller:
  JCasC:
    enabled: true
    defaultConfig: false
    config: {}
    configMaps:
      - jenkins-jcasc-config

  env:
    - name: JENKINS_ADMIN_PASSWORD
      valueFrom:
        secretKeyRef:
          name: jenkins-admin-secret
          key: JENKINS_ADMIN_PASSWORD

persistence:
  enabled: true
  existingClaim: jenkins-home