#controller:
#  installPlugins:
#    - kubernetes
#    - configuration-as-code
#    - workflow-aggregator
#    - git
#    - dark-theme

#  JCasC:
#    enabled: false
#    configMaps:
#      - jenkins-jcasc
#controller:
#  JCasC:
#    enabled: true
#    defaultConfig: false
#    configMaps:
#      - jenkins-config

persistence:
  enabled: true
  existingClaim: jenkins-home