apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel-infra
  namespace: observability
spec:
  mode: daemonset
  image: otel/opentelemetry-collector-contrib:latest
  podSecurityContext:
    runAsUser: 0
    runAsGroup: 0
  volumes:
    - name: hostfs
      hostPath:
        path: /
  config:
    receivers:
      hostmetrics:
        root_path: /hostfs
        collection_interval: 20s
        scrapers:
          cpu: {}
          memory: {}
          network: {}
          disk: {}
          filesystem: {}

      kubeletstats:
        collection_interval: 20s
        endpoint: "https://${env:K8S_NODE_NAME}:10250"
        auth_type: "serviceAccount"
        insecure_skip_verify: true

    processors:
      batch: {}

      resourcedetection:
        detectors: [env, system]

    exporters:
      debug:
        verbosity: normal
      prometheus_remotewrite:
        endpoint: "http://vmsingle-victoria-metrics-single-server.observability.svc.cluster.local:8428/api/v1/write"
        resource_to_telemetry_conversion:
          enabled: true

    service:
      pipelines:
        metrics:
          receivers: [hostmetrics, kubeletstats, prometheus]
          processors: [resourcedetection, batch]
          exporters: [debug, prometheus_remotewrite]

  volumeMounts:
    - name: hostfs
      mountPath: /hostfs
      readOnly: true
      mountPropagation: HostToContainer