apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflared-credential-token
  namespace: cloudflared
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical-cloud
    kind: ClusterSecretStore
  target:
    name: cloudflared-credential-token
    creationPolicy: Owner
  data:
    - secretKey: credentials.json
      remoteRef:
        key: /cloudflared/credentials.json