apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: cloudflared
    releaseName: cloudflared
    version: 2.0.9
    repo: https://community-charts.github.io/helm-charts
    namespace: external-dns
    valuesFile: values.yaml