tunnelSecrets:
  existingSecret: cloudflared-credentials-token
  secretKey: credentials.json

tunnelConfig:
  name: homelab-tunnel
  noAutoUpdate: true
  logLevel: info

ingress:
  - hostname: jenkins.serhii.link
    service: http://jenkins.jenkins.svc.cluster.local:8080
  - service: http_status:404