cloudflare:
  tunnelName: wildcard-tunnel
  secretName: cloudflared-credential-token

  ingress:
    - hostname: jenkins.serhii.link
      service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local:80
    - hostname: "*"
      service: http_status:404

replicaCount: 1