apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: infisical-cloud
spec:
  provider:
    infisical:
      hostAPI: "https://app.infisical.com"
      auth:
        tokenAuthCredentials:
          accessToken:
              name: infisical-eso
              namespace: external-secrets
              key: SERVICE_TOKEN
      secretsScope:
        projectSlug: homelab-ixx-o
        environmentSlug: prod
        secretsPath: /
