apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel-gateway
  namespace: observability
spec:
  mode: deployment
  replicas: 1
  image: otel/opentelemetry-collector-contrib:latest

  config:
    receivers:

    tcplog/talos:
      tcp:
        listen_address: "0.0.0.0:6050"
      operators:
        - type: json_parser

#      tcplog/talos:
#        tcp:
#          listen_address: "0.0.0.0:6050"  # або інший порт, якщо змінив
#        operators:
#          - type: json_parser
#            timestamp:
#              layout: '%Y-%m-%dT%H:%M:%S.%fZ'
#              layout_type: gotime
#              parse_from: talos-time
#            severity:
#              parse_from: talos-level
#              mapping:
#                info: INFO
#                warn: WARN
#                error: ERROR
#                debug: DEBUG

      k8s_events:
        auth_type: serviceAccount
        namespaces: []

      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    processors:

      resource/cluster_logs:
        attributes:
          - key: service.name
            value: logs
            action: upsert
          - key: service.namespace
            value: cluster
            action: upsert

      resource/cluster_events:
        attributes:
          - key: service.name
            value: events
            action: upsert
          - key: service.namespace
            value: cluster
            action: upsert

      resource/service_logs:
        attributes:
          - key: service.name
            value: logs
            action: upsert
          - key: service.namespace
            value: service
            action: upsert

      transform/events:
        log_statements:
          - context: log
            statements:
              # 1. Set default severity for all events first
              - set(severity_number, 9)
              - set(severity_text, "INFO")

              # 2. Upgrade severity for specific error conditions
              - set(severity_number, 17) where attributes["k8s.event.reason"] == "OOMKilling"
              - set(severity_text, "ERROR") where attributes["k8s.event.reason"] == "OOMKilling"

              - set(severity_number, 17) where attributes["k8s.event.reason"] == "FailedScheduling"
              - set(severity_text, "ERROR") where attributes["k8s.event.reason"] == "FailedScheduling"

              - set(severity_number, 17) where attributes["k8s.event.reason"] == "NodeNotReady"
              - set(severity_text, "ERROR") where attributes["k8s.event.reason"] == "NodeNotReady"

              # 3. Handle Warnings
              - set(severity_number, 13) where attributes["k8s.event.reason"] == "BackOff"
              - set(severity_text, "WARN") where attributes["k8s.event.reason"] == "BackOff"

      batch: {}

    exporters:
      prometheusremotewrite:
        endpoint: "http://victoria-metrics-victoria-metrics-single-server.observability.svc.cluster.local:8428/api/v1/write"
      debug: {}

      otlp_http/loki:
        endpoint: "http://loki.observability.svc:3100/otlp"

    service:
      pipelines:
#        metrics:
#          receivers: [otlp]
#          processors: [batch]
#          exporters: [prometheusremotewrite, debug]

        logs/talos:
          receivers: [ tcplog/talos ]
          processors: [ batch ]
          exporters: [ otlp_http/loki, debug ]  # або твій бекенд

        logs/cluster_events:
          receivers: [k8s_events]
          processors: [resource/cluster_events, transform/events, batch]
          exporters: [otlp_http/loki]

        logs/cluster_logs:
          receivers: [otlp]
          processors: [resource/cluster_logs, batch]
          exporters: [otlp_http/loki]