apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel-agent
  namespace: observability
spec:
  mode: daemonset
  image: otel/opentelemetry-collector-contrib:latest
  config:
    receivers:
      hostmetrics:
        scrapers:
          cpu: {}
          memory: {}
          network: {}
      kubeletstats:
        endpoint: "https://${env:K8S_NODE_NAME}:10250"
        auth_type: "serviceAccount"

    exporters:
      otlp:
        endpoint: "otel-gateway-collector.observability.svc.cluster.local:4317"
        tls:
          insecure: true

    service:
      pipelines:
        metrics:
          receivers: [hostmetrics, kubeletstats]
          exporters: [otlp]