apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: main-agent
  namespace: observability
spec:
  serviceScrapeNamespaceSelector: {}
  remoteWrite:
    - url: "http://victoria-metrics-server.observability.svc:8428/api/v1/write"
  serviceScrapeSelector:
    matchLabels:
      env: homelab