services:
  samba:
    image: servercontainers/samba
    container_name: samba
    networks:
      lan:
        ipv4_address: 192.168.1.60
    environment:
      - TZ=America/Los_Angeles
      - AVAHI_NAME=Share
    volumes:
      - /mnt/data/samba:/shares
      - ./smb.conf:/etc/samba/smb.conf:ro
    restart: unless-stopped
    logging:
      driver: json-file
      options: { max-size: "10m", max-file: "3" }

networks:
  lan:
    driver: macvlan
    driver_opts:
      parent: enp1s0
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1
          ip_range: 192.168.1.60/32
