services:
  samba:
    image: crazymax/samba:latest
    container_name: samba
    network_mode: host
    environment:
      - TZ=America/Los_Angeles
    volumes:
      - /mnt/data/samba:/shares/samba
      - ./smb.conf:/etc/samba/smb.conf:ro
    restart: unless-stopped