[global]
  workgroup = WORKGROUP
  security = user
  map to guest = Bad User
  guest account = nobody

# [Samba]
#   path = /mnt/data/samba
#   browseable = yes
#   writable = yes
#   guest ok = yes
#   force user = nobody
#   create mask = 0666
#   directory mask = 0777

[Scan]
  path = /mnt/data/scan
  browseable = yes
  writable = yes
  guest ok = yes
  force user = nobody

[Torrents]
  path = /mnt/data/torrents
  browseable = yes
  writable = yes
  guest ok = yes
  force user = nobody