[global]
  workgroup = WORKGROUP
  server string = Samba Server
  netbios name = SAMBA
  security = user
  map to guest = Bad User
  guest account = nobody
  disable spoolss = yes
  load printers = no

[samba]
  path = /shares/samba
  browseable = yes
  writable = yes
  guest ok = yes
  force user = nobody
  create mask = 0666
  directory mask = 0777