apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oauth2-proxy-token
  namespace: oauth2-proxy
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical-cloud
    kind: ClusterSecretStore
  target:
    name: oauth2-proxy-token
    creationPolicy: Owner
  data:
    - secretKey: cookie-secret
      remoteRef:
        key: /oauth2-proxy/cookie-secret
    - secretKey: client-secret
      remoteRef:
        key: /oauth2-proxy/client-secret
    - secretKey: client-id
      remoteRef:
        key: /oauth2-proxy/client-id