apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: gha-runner-scale-set-controller
    releaseName: gha-runner-scale-set-controller
    version: 0.8.2
    repo:  https://actions-runner-controller.github.io/actions-runner-controller
#    valuesFile: values.yaml
    namespace: actions-actions-runner-set

resources:
  - namespace.yaml
  - controller-manager-secret.yaml